/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:929d8575-f07b-43b7-9635-ec9edb7a3d5e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_SiN7Dbups",
    "aws_user_pools_web_client_id": "2oese5bgu1c6ougo9pclvvgcn1",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://b7q6tg6agvajxp7a77hpvkiuve.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-42kdiroxdfhwnkjhdsrpeq4uca",
    "aws_user_files_s3_bucket": "bucketofimages90634-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
